# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MN4armhu4K4BnamIDMrHeulME-lvvMB9
"""

from flask import Flask, Response, request
from camera_backend import camera_manager
import time

app = Flask(__name__)

@app.route('/video')

@app.route('/stop')
def stop():
    camera_manager.stop_streaming()
    return "Camera stopped"

if __name__ == '__main__':
    try:
        camera_manager.initialize_camera()
        app.run(host='0.0.0.0', port=5000)
    finally:
        camera_manager.stop_streaming()